### ISSUE TITLE
Wrong preprocessing

### ISSUE THREAD

**Issue by petrLorenc** [sebischair/NLU-Evaluation-Scripts#2]
Use according example
```
##rasa
rasa_analyser = RasaAnalyser("http://localhost:5000/parse")
rasa_analyser.get_annotations("WebApplicationsCorpus.json", "WebApplicationsAnnotations_Rasa.json")
rasa_analyser.analyse_annotations("WebApplicationsAnnotations_Rasa.json", "WebApplicationsCorpus.json", "WebApplicationsAnalysis_Rasa.json")
```
and get
```
Traceback (most recent call last):
  File "example.py", line 46, in <module>
    rasa_analyser.analyse_annotations("WebApplicationsAnnotations_Rasa.json", "WebApplicationsCorpus.json", "WebApplicationsAnalysis_Rasa.json")
  File "/Users/petr.lorenc/Documents/alquist/master-project/code/github/NLU-Evaluation-Scripts/nlu_analysers/luis_analyser.py", line 41, in analyse_annotations
    if not a["query"] == gold_standard[i]["text"]:
KeyError: 'query'
```
while `WebApplicationsAnnotations_Rasa.json` look like this
```
{
    "results": [
        {
            "project": "default",
            "entities": [],
            "model": "fallback",
            "intent": {
                "confidence": 1.0,
                "name": null
            },
            "text": "Alternative to Facebook"
        },
        {
            "project": "default",
            "entities": [],
            "model": "fallback",
            "intent": {
                "confidence": 1.0,
                "name": null
            },
            "text": "How do I delete my Facebook account?"
        },
...
```
I think that it is due some problem with format.

**Comment by AsyncSan** [comment]
Try changing
if not a["query"] == gold_standard[i]["text"]:
to

if not a["text"] == gold_standard[i]["text"]:

The Fields name is "text" and not query. Not sure why they uploaded it that way though
